# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        repository: godotengine/godot
        ref: 3.2
        path: build

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: build/modules/llightmap/ 

    - name: Show folders before
      run: pwd && whoami && ls -R

    # Use python 3.x release (works cross platform; best to keep self contained in it's own step)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'

    # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons pywin32
        python --version
        scons --version
        
    - name: Show folders after
      run: pwd && whoami && ls -R
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-editor (x64)
        path: build/bin/godot.windows.opt.tools.64.exe
        #path: build/modules/llightmap/README.md
